---
- name: Install Docker
  ansible.builtin.import_tasks: docker.yml
  tags:
    - docker

- name: Configure n8n stack
  ansible.builtin.import_tasks: n8n.yml
  tags:
    - n8n

- name: Configure n8n backup
  ansible.builtin.import_tasks: backup.yml
  tags:
    - n8n_backup
