---
control_node_terraform_version: "1.7.5"
control_node_terragrunt_version: "0.55.1"

control_node_sudo_user_name: "tech"
control_node_sudo_user_shell: "/bin/ash"
control_node_sudo_group: "wheel"
control_node_sudo_user_passwordless: false
