---
- name: Update apk package index
  community.general.apk:
    update_cache: true
  become: true

- name: Install essential system packages
  community.general.apk:
    name:
      - curl
      - unzip
      - jq
      - yq
      - make
      - yamllint
      - ansible-lint
      - jmespath
      - direnv
      - sops
      - gnupg
      - openssh-client
      - openssl
      - apg
      - pwgen
      - gcompat
      - vim
      - wget
      - tmux
      - nano
      - neovim
      - build-base
      - ripgrep
      - fd
      - nodejs
      - npm
      - lazygit
      - lazydocker
      - mariadb-client
      - bat
      - sudo
    state: present
  become: true
  tags:
    - install_software

- name: Ensure sudo group exists
  ansible.builtin.group:
    name: "{{ control_node_sudo_group }}"
    state: present
  become: true

- name: Ensure privileged user exists
  ansible.builtin.user:
    name: "{{ control_node_sudo_user_name }}"
    shell: "{{ control_node_sudo_user_shell }}"
    groups:
      - "{{ control_node_sudo_group }}"
    append: true
    create_home: true
    state: present
  become: true

- name: Ensure sudoers.d directory exists
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: "0750"
  become: true

- name: Configure sudo privileges for privileged user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ control_node_sudo_user_name }}"
    content: |
      {{ control_node_sudo_user_name }} ALL=(ALL:ALL) {{ 'NOPASSWD:' if control_node_sudo_user_passwordless else '' }}ALL
    owner: root
    group: root
    mode: "0440"
  become: true

- name: Configure Git global settings
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.name", value: "Hydra Commander" }
    - { name: "user.email", value: "tech@devgru.com.pl" }
    - { name: "pull.rebase", value: "false" }
  become: true
