all:
  hosts:
    cloud-host1:
      ansible_host: 1.2.3.4
      ansible_user: ansible
    cloud-host2:
      ansible_host: 1.2.3.5
      ansible_user: ansible
    on-prem-host:
      ansible_host: 1.2.3.6
      ansible_user: ansible
    on-prem-host2:
      ansible_host: 1.2.3.7
      ansible_user: ansible

  children:
    cloud:
      hosts:
        cloud-host1:
        cloud-host2:
    on-prem:
      hosts:
        on-prem-host:
        on-prem-host2:
    n8n-server:
      vars:
        n8n_port: 8080
        n8n_domain: n8n.example.com
      hosts:
        cloud-host1:
        cloud-host2:
    n8n_compose:
      vars:
        n8n_port: "5678"
        n8n_domain: n8n.example.com
        n8n_db_password: "changeme"
      hosts:
        cloud-host1:
